name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Issue is looking mighty stale'
        stale-pr-message: 'Somebody think of the PRs!'
        stale-issue-label: 'stale-issue'
        stale-pr-label: 'stale-pr'
        days-before-stale: 30
        days-before-close: 5
        exempt-issue-label: 'approved'
        exempt-pr-label: 'approved'
